In [1]:
from nba_api.stats.static import teams
from nba_api.stats.endpoints import leaguegamefinder
from elasticsearch import Elasticsearch, helpers
from getpass import getpass
from io import StringIO
import pandas as pd

In [2]:
nba_teams = teams.get_teams()

In [4]:
nba_teams

[{'id': 1610612737,
  'full_name': 'Atlanta Hawks',
  'abbreviation': 'ATL',
  'nickname': 'Hawks',
  'city': 'Atlanta',
  'state': 'Georgia',
  'year_founded': 1949},
 {'id': 1610612738,
  'full_name': 'Boston Celtics',
  'abbreviation': 'BOS',
  'nickname': 'Celtics',
  'city': 'Boston',
  'state': 'Massachusetts',
  'year_founded': 1946},
 {'id': 1610612739,
  'full_name': 'Cleveland Cavaliers',
  'abbreviation': 'CLE',
  'nickname': 'Cavaliers',
  'city': 'Cleveland',
  'state': 'Ohio',
  'year_founded': 1970},
 {'id': 1610612740,
  'full_name': 'New Orleans Pelicans',
  'abbreviation': 'NOP',
  'nickname': 'Pelicans',
  'city': 'New Orleans',
  'state': 'Louisiana',
  'year_founded': 2002},
 {'id': 1610612741,
  'full_name': 'Chicago Bulls',
  'abbreviation': 'CHI',
  'nickname': 'Bulls',
  'city': 'Chicago',
  'state': 'Illinois',
  'year_founded': 1966},
 {'id': 1610612742,
  'full_name': 'Dallas Mavericks',
  'abbreviation': 'DAL',
  'nickname': 'Mavericks',
  'city': 'Dallas',
  'state': 'Texas',
  'year_founded': 1980},
 {'id': 1610612743,
  'full_name': 'Denver Nuggets',
  'abbreviation': 'DEN',
  'nickname': 'Nuggets',
  'city': 'Denver',
  'state': 'Colorado',
  'year_founded': 1976},
 {'id': 1610612744,
  'full_name': 'Golden State Warriors',
  'abbreviation': 'GSW',
  'nickname': 'Warriors',
  'city': 'Golden State',
  'state': 'California',
  'year_founded': 1946},
 {'id': 1610612745,
  'full_name': 'Houston Rockets',
  'abbreviation': 'HOU',
  'nickname': 'Rockets',
  'city': 'Houston',
  'state': 'Texas',
  'year_founded': 1967},
 {'id': 1610612746,
  'full_name': 'Los Angeles Clippers',
  'abbreviation': 'LAC',
  'nickname': 'Clippers',
  'city': 'Los Angeles',
  'state': 'California',
  'year_founded': 1970},
 {'id': 1610612747,
  'full_name': 'Los Angeles Lakers',
  'abbreviation': 'LAL',
  'nickname': 'Lakers',
  'city': 'Los Angeles',
  'state': 'California',
  'year_founded': 1948},
 {'id': 1610612748,
  'full_name': 'Miami Heat',
  'abbreviation': 'MIA',
  'nickname': 'Heat',
  'city': 'Miami',
  'state': 'Florida',
  'year_founded': 1988},
 {'id': 1610612749,
  'full_name': 'Milwaukee Bucks',
  'abbreviation': 'MIL',
  'nickname': 'Bucks',
  'city': 'Milwaukee',
  'state': 'Wisconsin',
  'year_founded': 1968},
 {'id': 1610612750,
  'full_name': 'Minnesota Timberwolves',
  'abbreviation': 'MIN',
  'nickname': 'Timberwolves',
  'city': 'Minnesota',
  'state': 'Minnesota',
  'year_founded': 1989},
 {'id': 1610612751,
  'full_name': 'Brooklyn Nets',
  'abbreviation': 'BKN',
  'nickname': 'Nets',
  'city': 'Brooklyn',
  'state': 'New York',
  'year_founded': 1976},
 {'id': 1610612752,
  'full_name': 'New York Knicks',
  'abbreviation': 'NYK',
  'nickname': 'Knicks',
  'city': 'New York',
  'state': 'New York',
  'year_founded': 1946},
 {'id': 1610612753,
  'full_name': 'Orlando Magic',
  'abbreviation': 'ORL',
  'nickname': 'Magic',
  'city': 'Orlando',
  'state': 'Florida',
  'year_founded': 1989},
 {'id': 1610612754,
  'full_name': 'Indiana Pacers',
  'abbreviation': 'IND',
  'nickname': 'Pacers',
  'city': 'Indiana',
  'state': 'Indiana',
  'year_founded': 1976},
 {'id': 1610612755,
  'full_name': 'Philadelphia 76ers',
  'abbreviation': 'PHI',
  'nickname': '76ers',
  'city': 'Philadelphia',
  'state': 'Pennsylvania',
  'year_founded': 1949},
 {'id': 1610612756,
  'full_name': 'Phoenix Suns',
  'abbreviation': 'PHX',
  'nickname': 'Suns',
  'city': 'Phoenix',
  'state': 'Arizona',
  'year_founded': 1968},
 {'id': 1610612757,
  'full_name': 'Portland Trail Blazers',
  'abbreviation': 'POR',
  'nickname': 'Trail Blazers',
  'city': 'Portland',
  'state': 'Oregon',
  'year_founded': 1970},
 {'id': 1610612758,
  'full_name': 'Sacramento Kings',
  'abbreviation': 'SAC',
  'nickname': 'Kings',
  'city': 'Sacramento',
  'state': 'California',
  'year_founded': 1948},
 {'id': 1610612759,
  'full_name': 'San Antonio Spurs',
  'abbreviation': 'SAS',
  'nickname': 'Spurs',
  'city': 'San Antonio',
  'state': 'Texas',
  'year_founded': 1976},
 {'id': 1610612760,
  'full_name': 'Oklahoma City Thunder',
  'abbreviation': 'OKC',
  'nickname': 'Thunder',
  'city': 'Oklahoma City',
  'state': 'Oklahoma',
  'year_founded': 1967},
 {'id': 1610612761,
  'full_name': 'Toronto Raptors',
  'abbreviation': 'TOR',
  'nickname': 'Raptors',
  'city': 'Toronto',
  'state': 'Ontario',
  'year_founded': 1995},
 {'id': 1610612762,
  'full_name': 'Utah Jazz',
  'abbreviation': 'UTA',
  'nickname': 'Jazz',
  'city': 'Utah',
  'state': 'Utah',
  'year_founded': 1974},
 {'id': 1610612763,
  'full_name': 'Memphis Grizzlies',
  'abbreviation': 'MEM',
  'nickname': 'Grizzlies',
  'city': 'Memphis',
  'state': 'Tennessee',
  'year_founded': 1995},
 {'id': 1610612764,
  'full_name': 'Washington Wizards',
  'abbreviation': 'WAS',
  'nickname': 'Wizards',
  'city': 'Washington',
  'state': 'District of Columbia',
  'year_founded': 1961},
 {'id': 1610612765,
  'full_name': 'Detroit Pistons',
  'abbreviation': 'DET',
  'nickname': 'Pistons',
  'city': 'Detroit',
  'state': 'Michigan',
  'year_founded': 1948},
 {'id': 1610612766,
  'full_name': 'Charlotte Hornets',
  'abbreviation': 'CHA',
  'nickname': 'Hornets',
  'city': 'Charlotte',
  'state': 'North Carolina',
  'year_founded': 1988}]

In [5]:
celtics = [team for team in nba_teams if team['abbreviation'] == 'BOS'][0]

In [6]:
timberwolves = [team for team in nba_teams if team['abbreviation'] == 'MIN'][0]

In [7]:
celtics_id = celtics['id']

In [8]:
timberwolves_id = timberwolves['id']

In [9]:
celtics_gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=celtics_id)
celtics_games = celtics_gamefinder.get_data_frames()[0]
celtics_games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,42023,1610612738,BOS,Boston Celtics,0042300304,2024-05-27,BOS @ IND,W,240,105,...,0.786,12,32,44,22,10,6,11,18,3.0
1,42023,1610612738,BOS,Boston Celtics,0042300303,2024-05-25,BOS @ IND,W,239,114,...,0.769,7,29,36,24,7,12,7,18,3.0
2,42023,1610612738,BOS,Boston Celtics,0042300302,2024-05-23,BOS vs. IND,W,239,126,...,0.850,13,27,40,28,9,2,10,16,16.0
3,42023,1610612738,BOS,Boston Celtics,0042300301,2024-05-21,BOS vs. IND,W,265,133,...,0.800,13,30,43,30,11,5,14,15,5.0
4,42023,1610612738,BOS,Boston Celtics,0042300205,2024-05-15,BOS vs. CLE,W,239,113,...,0.833,11,32,43,32,6,6,12,15,15.0

In [10]:
timberwolves_gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=timberwolves_id)
timberwolves_games = timberwolves_gamefinder.get_data_frames()[0]
timberwolves_games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,42023,1610612750,MIN,Minnesota Timberwolves,0042300315,2024-05-30,MIN vs. DAL,L,240,103,...,0.810,13,28,41,17,8,5,11,17,-21.0
1,42023,1610612750,MIN,Minnesota Timberwolves,0042300314,2024-05-28,MIN @ DAL,W,240,105,...,0.640,6,34,40,23,9,4,14,23,5.0
2,42023,1610612750,MIN,Minnesota Timberwolves,0042300313,2024-05-26,MIN @ DAL,L,239,107,...,0.706,10,23,33,26,4,2,10,24,-9.0
3,42023,1610612750,MIN,Minnesota Timberwolves,0042300312,2024-05-24,MIN vs. DAL,L,239,108,...,0.813,12,28,40,26,7,7,9,19,-1.0
4,42023,1610612750,MIN,Minnesota Timberwolves,0042300311,2024-05-22,MIN vs. DAL,L,240,105,...,0.611,10,30,40,23,8,3,10,17,-3.0

In [10]:
celtics_current_season = celtics_games.loc[(celtics_games['GAME_DATE'] >= '2023-10-24') & (celtics_games['GAME_DATE'] <= '2024-06-20')]
celtics_current_season

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,42023,1610612738,BOS,Boston Celtics,0042300304,2024-05-27,BOS @ IND,W,240,105,...,0.786,12,32,44,22,10,6,11,18,3.0
1,42023,1610612738,BOS,Boston Celtics,0042300303,2024-05-25,BOS @ IND,W,239,114,...,0.769,7,29,36,24,7,12,7,18,3.0
2,42023,1610612738,BOS,Boston Celtics,0042300302,2024-05-23,BOS vs. IND,W,239,126,...,0.850,13,27,40,28,9,2,10,16,16.0
3,42023,1610612738,BOS,Boston Celtics,0042300301,2024-05-21,BOS vs. IND,W,265,133,...,0.800,13,30,43,30,11,5,14,15,5.0
4,42023,1610612738,BOS,Boston Celtics,0042300205,2024-05-15,BOS vs. CLE,W,239,113,...,0.833,11,32,43,32,6,6,12,15,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,22023,1610612738,BOS,Boston Celtics,0022300136,2023-11-04,BOS @ BKN,W,240,124,...,0.852,10,40,50,22,4,6,11,17,10.0
92,22023,1610612738,BOS,Boston Celtics,0022300118,2023-11-01,BOS vs. IND,W,239,155,...,0.964,11,46,57,27,5,2,11,19,51.0
93,22023,1610612738,BOS,Boston Celtics,0022300103,2023-10-30,BOS @ WAS,W,243,126,...,0.714,15,36,51,31,11,6,17,21,19.0
94,22023,1610612738,BOS,Boston Celtics,0022300080,2023-10-27,BOS vs. MIA,W,239,119,...,0.684,16,39,55,20,7,6,15,19,8.0
95,22023,1610612738,BOS,Boston Celtics,0022300065,2023-10-25,BOS @ NYK,W,241,108,...,0.846,7,39,46,18,6,11,13,22,4.0

In [12]:
celtics_current_season.isnull().values.any()

True

In [14]:
timberwolves_current_season = timberwolves_games.loc[(timberwolves_games['GAME_DATE'] >= '2023-10-24') & (timberwolves_games['GAME_DATE'] <= '2024-06-20')]
timberwolves_current_season

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,42023,1610612750,MIN,Minnesota Timberwolves,0042300315,2024-05-30,MIN vs. DAL,L,240,103,...,0.810,13,28,41,17,8,5,11,17,-21.0
1,42023,1610612750,MIN,Minnesota Timberwolves,0042300314,2024-05-28,MIN @ DAL,W,240,105,...,0.640,6,34,40,23,9,4,14,23,5.0
2,42023,1610612750,MIN,Minnesota Timberwolves,0042300313,2024-05-26,MIN @ DAL,L,239,107,...,0.706,10,23,33,26,4,2,10,24,-9.0
3,42023,1610612750,MIN,Minnesota Timberwolves,0042300312,2024-05-24,MIN vs. DAL,L,239,108,...,0.813,12,28,40,26,7,7,9,19,-1.0
4,42023,1610612750,MIN,Minnesota Timberwolves,0042300311,2024-05-22,MIN vs. DAL,L,240,105,...,0.611,10,30,40,23,8,3,10,17,-3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,22023,1610612750,MIN,Minnesota Timberwolves,0022300138,2023-11-04,MIN vs. UTA,W,242,123,...,0.774,9,34,43,25,10,11,10,23,28.0
94,22023,1610612750,MIN,Minnesota Timberwolves,0022300123,2023-11-01,MIN vs. DEN,W,239,110,...,0.963,8,39,47,20,9,5,13,15,21.0
95,22023,1610612750,MIN,Minnesota Timberwolves,0022300104,2023-10-30,MIN @ ATL,L,240,113,...,0.600,10,28,38,24,5,5,10,17,-14.0
96,22023,1610612750,MIN,Minnesota Timberwolves,0022300093,2023-10-28,MIN vs. MIA,W,240,106,...,0.750,7,40,47,30,9,3,14,17,16.0
97,22023,1610612750,MIN,Minnesota Timberwolves,0022300069,2023-10-25,MIN @ TOR,L,240,94,...,0.818,16,46,62,20,8,9,14,14,-3.0

In [15]:
timberwolves_current_season.isnull().values.any()

False

In [16]:
celtics_current_season_copy = celtics_current_season.copy()

celtics_current_season_copy.fillna(0, inplace=True)

In [17]:
es = Elasticsearch(
    getpass("Host: "),
    api_key=getpass("API Key: "),
)

Host:  ········
API Key:  ········

In [18]:
celtics_index_name = "osn_prac_demo_celtics"

In [19]:
timberwolves_index_name = "osn_prac_demo_timberwolves"

In [20]:
es.indices.create(index=celtics_index_name)

ObjectApiResponse({'acknowledged': True, 'shards_acknowledged': True, 'index': 'osn_prac_demo_celtics'})

In [21]:
es.indices.create(index=timberwolves_index_name)

ObjectApiResponse({'acknowledged': True, 'shards_acknowledged': True, 'index': 'osn_prac_demo_timberwolves'})

In [22]:
def doc_generator(df, timeframe):
    for index, document in df.iterrows():
        yield {
            "_index": timeframe, 
            "_id": f"{document['GAME_ID']}",
            "_source": document.to_dict(),
        }

In [23]:
helpers.bulk(es, doc_generator(celtics_current_season_copy, celtics_index_name))

(96, [])

In [24]:
helpers.bulk(es, doc_generator(timberwolves_current_season, timberwolves_index_name))

(98, [])

In [25]:
search_query = {
    "query": {
        "match": {
            "WL": "W"
        }
    }
}

In [26]:
celtics_games_won = es.count(index=celtics_index_name, body=search_query)
timberwolves_games_won = es.count(index=timberwolves_index_name, body=search_query)

In [27]:
celtics_games_won

ObjectApiResponse({'count': 76, '_shards': {'total': 1, 'successful': 1, 'skipped': 0, 'failed': 0}})

In [28]:
timberwolves_games_won

ObjectApiResponse({'count': 65, '_shards': {'total': 1, 'successful': 1, 'skipped': 0, 'failed': 0}})

In [29]:
print(f"The Celtics won {celtics_games_won['count']} games this season so far.")

The Celtics won 76 games this season so far.

In [30]:
print(f"The Timberwolves won {timberwolves_games_won['count']} games this season so far.")

The Timberwolves won 65 games this season so far.

In [31]:
streak_query = {
  "size": 1000,  
  "sort": [
    {
      "GAME_DATE": {
        "order": "asc"
      }
    }
  ],
  "_source": ["GAME_DATE", "WL"]
}

In [32]:
celtics_streak_search = es.search(index=celtics_index_name, body=streak_query)

In [33]:
timberwolves_strek_search = es.search(index=timberwolves_index_name, body=streak_query)

In [34]:
cs = [hit['_source'] for hit in celtics_streak_search['hits']['hits']]

In [35]:
ts = [hit['_source'] for hit in timberwolves_strek_search['hits']['hits']]

In [36]:
# celtics top 5 streaks

In [37]:
streaks = []
current_streak = 1
for i in range(1, len(cs)):
    if cs[i]['WL'] == cs[i-1]['WL']:
        current_streak += 1
    else:
        streaks.append((cs[i-1]['WL'], current_streak))
        current_streak = 1


streaks.append((cs[-1]['WL'], current_streak))
top_streaks = sorted(streaks, key=lambda x: x[1], reverse=True)[:5]
print(top_streaks)

[('W', 11), ('W', 9), ('W', 7), ('W', 6), ('W', 6)]

In [68]:
# timberwolves top 5 streaks

In [38]:
streaks = []
current_streak = 1
for i in range(1, len(ts)):
    if ts[i]['WL'] == ts[i-1]['WL']:
        current_streak += 1
    else:
        streaks.append((ts[i-1]['WL'], current_streak))
        current_streak = 1


streaks.append((ts[-1]['WL'], current_streak))
top_streaks = sorted(streaks, key=lambda x: x[1], reverse=True)[:5]
print(top_streaks)

[('W', 7), ('W', 6), ('W', 6), ('W', 4), ('W', 4)]

In [40]:
celtics_fg_stats = es.esql.query(
    query="FROM osn_prac_celtics | STATS AVG(FG_PCT), AVG(FG3_PCT) | LIMIT 1",
    format="csv",
)

In [41]:
celtics_fg_stats_df = pd.read_csv(StringIO(celtics_fg_stats.body))
celtics_fg_stats_df

   AVG(FG_PCT)  AVG(FG3_PCT)
0     0.486763      0.385312

In [43]:
timberwolves_fg_stats = es.esql.query(
    query="FROM osn_prac_timberwolves | STATS AVG(FG_PCT), AVG(FG3_PCT) | LIMIT 1",
    format="csv",
)

In [44]:
timberwolves_fg_stats_df = pd.read_csv(StringIO(timberwolves_fg_stats.body))
timberwolves_fg_stats_df

   AVG(FG_PCT)  AVG(FG3_PCT)
0     0.484096      0.383309